name: Alpha
description: Get3w Documentions
baseurl: ''
url: ''
highlight: pygments
disqus: get3wcom

# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        /:title

exclude: ['Rakefile','.gitignore','.gitignore']

# # PAGINATION
# gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "page:num"
branches:
  only:
    - gh-pages

repository: https://github.com/get3w/get3w
help_url: https://github.com/get3w/get3w-help
